spring:
  datasource:
    url: jdbc:mysql://mainline.proxy.rlwy.net:58786/cicd_db
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: ${PORT:8080}

logging:
  level:
    com.oocl.springbootemployee: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 修复Actuator metrics在容器环境的问题
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      jmx:
        enabled: false
    enable:
      # 禁用有问题的processor和system metrics
      process: false
      system: false
