spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cicd_db?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

server:
  port: ${PORT:8080}